V2/dev smartassist stat 4654
Koredotcom/web-kore-sdk pull request #58
Opened 2022-11-30 13:35 UTC by santhoshvishalve-Kore

2022-12-01 08:05 UTC, KambagiriswamyBo-Kore requested changes

2022-12-01 08:05 UTC, KambagiriswamyBo-Kore commented on src/plugins/agentDesktop/agentdesktop.ts
> +                    }
@santhoshvishalve-Kore Make sure the have only desktop notifications related changes in the PR.

2022-12-01 08:05 UTC, KambagiriswamyBo-Kore commented on src/plugins/desktopNotifications/desktopnotifications.ts
> +    appendVideoAudioElemnts() {
@santhoshvishalve-Kore  Why do we need appendVideoAudioElemnts method in desktop notifications plugin?

2022-12-02 06:44 UTC, santhoshvishalve-Kore commented
@KambagiriswamyBo-Kore changes has been done.

2022-12-05 15:09 UTC, closed without merging